server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: ${APP_NAME:paste-king}
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/paste_king}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:change_me}
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

springdoc:
  api-docs:
    enabled: ${APP_SWAGGER_ENABLED:false}
  swagger-ui:
    enabled: ${APP_SWAGGER_ENABLED:false}
    path: /swagger

app:
  jwt:
    secret: ${APP_JWT_SECRET}
    expiration: ${APP_JWT_EXPIRATION:PT8H}
  initial-user:
    login: ${APP_INITIAL_LOGIN:admin}
    password: ${APP_INITIAL_PASSWORD:change_me}
